//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.tripadvisor.drawisor;


public final class DrawisorApplication_
    extends DrawisorApplication
{


    private void init_() {
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

}
