//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.tripadvisor.drawisor.activities;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.FrameLayout;
import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuInflater;
import com.actionbarsherlock.view.MenuItem;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import com.tripadvisor.drawisor.R.layout;

public final class DrawingActivity_
    extends DrawingActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_drawing);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        sizeButton = ((Button) findViewById(com.tripadvisor.drawisor.R.id.sizeButton));
        colorButton = ((Button) findViewById(com.tripadvisor.drawisor.R.id.colorButton));
        placeholder = ((FrameLayout) findViewById(com.tripadvisor.drawisor.R.id.placeholder));
        {
            View view = findViewById(com.tripadvisor.drawisor.R.id.undoButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DrawingActivity_.this.undoButtonClicked();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.tripadvisor.drawisor.R.id.clearButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DrawingActivity_.this.clearButtonClicked();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.tripadvisor.drawisor.R.id.redoButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DrawingActivity_.this.redoButtonClicked();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.tripadvisor.drawisor.R.id.sizeButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DrawingActivity_.this.sizeButtonClicked();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.tripadvisor.drawisor.R.id.colorButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DrawingActivity_.this.colorButtonClicked();
                    }

                }
                );
            }
        }
        start();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static DrawingActivity_.IntentBuilder_ intent(Context context) {
        return new DrawingActivity_.IntentBuilder_(context);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getSupportMenuInflater();
        menuInflater.inflate(com.tripadvisor.drawisor.R.menu.activity_drawing, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean handled = super.onOptionsItemSelected(item);
        if (handled) {
            return true;
        }
        int itemId_ = item.getItemId();
        if (itemId_ == com.tripadvisor.drawisor.R.id.save) {
            save();
            return true;
        }
        if (itemId_ == android.R.id.home) {
            home();
            return true;
        }
        return false;
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, DrawingActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public DrawingActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
